fix: SDA-2644 (Fix snippet window resize issue based on screen size)
symphonyoss/SymphonyElectron pull request #1115
Opened 2020-11-18 09:39 UTC by KiranNiranjan

## Description
- Resize image based on screen size
[SDA-2644](https://perzoinc.atlassian.net/browse/SDA-2644)

## Solution Approach
- Calculate the screen and image height

## Screencast
![2020-11-18 15 05 47](https://user-images.githubusercontent.com/13243259/99512682-c40af480-29af-11eb-9271-556877e6c15e.gif)

Notes: Fix the screen snippet window size issue

2020-11-18 11:03 UTC, psjostrom requested changes
Codewise it looks great, functionalitywise I am missing three things that I have told you about in chat :)

2020-11-19 05:49 UTC, keerthi16 approved these changes

2020-11-19 08:32 UTC, KiranNiranjan commented
No @psjostrom both window and the image size are sized down

2020-11-19 08:37 UTC, psjostrom commented
Awesome!

2020-11-19 12:27 UTC, psjostrom approved these changes

2020-11-19 13:34 UTC, merged